---
apiVersion: v1
kind: Service
metadata:
  name: spark-history-service
  namespace: spark
  labels:
    app: spark-history
spec:
  ports:
  - port: 18080
    targetPort: 18080
    protocol: TCP
    name: http
  selector:
    app: spark-history