# Hack: Used to give ArgoWorkflow the ability to check the deployment status with our script
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-deployment-status-cluster-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-deployment-status-cluster-rolebinding
  namespace: mlops-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-deployment-status-cluster-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: argo
---
# Allow Argo WF to create Argo Applications
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-application-cluster-role
rules:
- apiGroups:
  - argoproj.io
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-application-cluster-role-binding
  namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-application-cluster-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: argo
