# Used from Basic Auth: admin:password
# This is for using basic auth for JupyterHub
apiVersion: v1
data:
  auth: YWRtaW46JGFwcjEkODdYNk9JZXIkay9FYlBlM2hVWGtJTUplN2lMUk1jMAo=
kind: Secret
metadata:
  name: basic-auth
  namespace: jupyterhub
type: Opaque