apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- projects.yaml
- applications.yaml
# Hack because app of apps is not creating the namespaces
- namespaces.yaml
# Shitty hack for kind clusters for Jupyterhub
- auth-secret.yaml
