apiVersion: v1
kind: Namespace
metadata:
  name: argo
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: v1
kind: Namespace
metadata:
  name: mlops-test
---
apiVersion: v1
kind: Namespace
metadata:
  name: mlflow
