apiVersion: v1
kind: ConfigMap
metadata:
  name: mlgateway-configmap
  namespace: mlops
  labels:
    app: mlgateway
data:
  MLFLOW_ARTIFACT_URI: "http://mlflow-minio-service.mlflow.svc.cluster.local:9000"
  MLFLOW_TRACKING_URI: "http://mlflow-service.mlflow.svc.cluster.local:5000"