apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - argo-workflows.yaml
  - metrics-server.yaml
  - nginx-ingress.yaml
  - pipeline-configs.yaml
  - mlflow.yaml
  - jupyterhub.yaml
  - auth-secret.yaml
namespace: argocd