apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- github.com/argoproj/argo-cd/manifests/crds
- github.com/argoproj/argo-cd/manifests/base
- github.com/argoproj/argo-cd/manifests/cluster-rbac/
namespace: argocd
