apiVersion: v1
kind: ConfigMap
metadata:
  name: mlflow-minio-configmap
  namespace: mlflow
  labels:
    app: mlflow-minio
data:
  MINIO_SECRET_KEY: minio123
  MINIO_ACCESS_KEY: minio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-minio
  namespace: mlflow
spec:
  selector:
    matchLabels:
      app: mlflow-minio
  template:
    metadata:
      labels:
        app: mlflow-minio
    spec:
      containers:
      - name: mlflow-minio
        image: minio/minio:latest
        imagePullPolicy: IfNotPresent
        args:
        - server
        - /data
        volumeMounts:
        - name: mlflow-artifacts
          mountPath: '/data'
        envFrom:
          - configMapRef:
              name: mlflow-minio-configmap
        ports:
        - containerPort: 9000
      volumes:
        - name: mlflow-artifacts
          hostPath:
            path: /mnt/minio/mlflow
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-minio-service
  namespace: mlflow
  labels:
    app: mlflow-minio
spec:
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
  selector:
    app: mlflow-minio
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mlflow-minio-ingress
  namespace: mlflow
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: minio
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: mlflow-minio-service
              port:
                number: 9000
