apiVersion: v1
kind: ConfigMap
metadata:
  name: mlflow-postgres-configmap
  namespace: mlflow
  labels:
    app: mlflow-postgres
data:
  POSTGRES_DB: mlflow
  POSTGRES_USER: mlflow
  POSTGRES_PASSWORD: mlflowsecretpassword
  PGDATA: /var/lib/postgresql/mlflow/data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-postgres
  namespace: mlflow
  labels:
    app: mlflow-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-postgres
  template:
    metadata:
      labels:
        app: mlflow-postgres
    spec:
      containers:
      - name: mlflow-postgres
        image: postgres:13.2-alpine
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: mlflow-postgres-configmap
        resources:
          requests:
            memory: "200Mi"
            cpu: "500m"
        volumeMounts:
          - name: mlflow-backend
            mountPath: /var/lib/postgresql/mlflow
        ports:
          - containerPort: 5432
            protocol: TCP
      volumes:
        - name: mlflow-backend
          hostPath:
            path: /mnt/postgresql/mlflow
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-postgres-service
  namespace: mlflow
  labels:
    app: mlflow-postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: mlflow-postgres
