# Used from Basic Auth: admin:password
apiVersion: v1
data:
  auth: YWRtaW46JGFwcjEkODdYNk9JZXIkay9FYlBlM2hVWGtJTUplN2lMUk1jMAo=
kind: Secret
metadata:
  name: basic-auth
  namespace: argo
type: Opaque