apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - external-dns.yaml
  - prometheus.yaml
  - namespaces.yaml
patchesStrategicMerge:
- external-dns-deployment.yaml